# Site settings
title: LHCb Starterkit
email: lhcb-starterkit@cern.ch
description: This website contains all the information concerning the LHCb Starterkit.
baseurl: "/starterkit"
twitter_username: LHCbStarterkit
github_username:  lhcb
# Display posts with dates in the future
future: true

# Build settings
markdown: kramdown

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
    - vendor
